apiVersion: v1
kind: ConfigMap
metadata:
  name: msa3-svc-product
  namespace: msasmp01
data:
  application-dev.yml: |-
    spring:
      application:
        name: msa3-svc-product
    springfox:
      documentation:
        swagger:
          v2:
            path: /product/api-docs        
