apiVersion: v1
kind: ConfigMap
metadata:
  name: msa3-svc-member
  namespace: msasmp01
data:
  application-dev.yml: |-
    spring:
      application:
        name: msa3-svc-member
      data:
        mongodb:
          host: mongodb-standalone-0.mongodb
          username: user
          password: password
          database: sample01
          port: 27017
    springfox:
      documentation:
        swagger:
          v2:
            path: /member/api-docs        
