apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    run: msa3-svc-member
  name: msa3-svc-member
spec:
  replicas: 1
  selector:
    matchLabels:
      run: msa3-svc-member
  template:
    metadata:
      labels:
        run: msa3-svc-member
    spec:
      containers:
      - image: 192.168.100.102:5000/msasmp03/msa3-svc-member:1.0
        imagePullPolicy: Always
        name: msa3-svc-member
        ports:
        - containerPort: 9091
          protocol: TCP
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  labels:
    run: msa3-svc-member
  name: msa3-svc-member
spec:
  ports:
  - port: 9091
    protocol: TCP
    name: http
    targetPort: 9091
  selector:
    run: msa3-svc-member
  type: ClusterIP



