apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    run: msa3-svc-order
  name: msa3-svc-order
spec:
  replicas: 1
  selector:
    matchLabels:
      run: msa3-svc-order
  template:
    metadata:
      labels:
        run: msa3-svc-order
    spec:
      containers:
      - image: 192.168.100.102:5000/msasmp03/msa3-svc-order:1.0
        imagePullPolicy: Always
        name: msa3-svc-order
        ports:
        - containerPort: 9092
          protocol: TCP
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: msa3-svc-order
  name: msa3-svc-order
spec:
  ports:
  - port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    run: msa3-svc-order
  type: ClusterIP


